project 'Fch_Contact.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Fch_Contact' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

    pod 'SnapKit', '~> 4.0.0'
    pod 'RxSwift', '~> 4.0.0'
    pod 'RxCocoa', '~> 4.0.0'
#     pod 'RxDataSources', '~> 1.0.3'
    
    pod 'MJRefresh', '~> 3.1.12'
    pod 'HandyJSON', '4.0.0-beta.1'
#     pod 'HandyJSON', '1.7.2'
#    pod 'MJExtension', '~> 3.0.13'
    pod 'BAlertView', '~> 1.0.7'
    
    pod 'Alamofire', '~> 4.5.1'
    pod 'FMDB', '~> 2.7.2'
 #  pod 'Kingfisher', '~> 3.8.0'
   pod 'IQKeyboardManagerSwift', '~> 5.0.0'
   

    



end
