project 'ReactiveCocoaDemo.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '8.0'

target 'ReactiveCocoaDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'ReactiveCocoa', '~> 5.0.3'

end
