project 'ReactiveCocoaDemo.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '8.0'

target 'ReactiveCocoaDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!


  pod 'SnapKit', '~> 3.2.0'
  pod 'RxSwift',    '~> 3.4.1'
  pod 'RxCocoa',    '~> 3.4.1'
  pod 'MJRefresh'
  pod 'BAlertView'
  
end
